version: 0.2

phases: 
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - chmod +x build_image.sh push-image.sh
      - ./build_image.sh

  build:
    commands:
      - ./push-image.sh
